use std::{fs, io::Write, path::PathBuf, thread, time::Duration};
use anyhow::{Context, Result}; use reqwest::blocking::{multipart, Client}; use serde::{Deserialize, Serialize}; use uuid::Uuid;
use crate::capture::TrackKind; use super::{LocalTranscriptSegment, RecordingState, SessionStore, TrackProcessingState};
const CHUNK_SECONDS: usize = 25; const WAV_HEADER: usize = 44; const BYTES_PER_SECOND: usize = 48_000 * 2 * 2;
#[derive(Clone, Serialize, Deserialize)] struct Queue { items: Vec<QueueItem> }
#[derive(Clone, Serialize, Deserialize)] struct QueueItem { sequence: usize, start_ms: i64, end_ms: i64, path: String, state: String, attempts: u32, last_error: Option<String> }

/// One worker per session. It only reads completed windows; capture keeps sole ownership of the live track.
pub fn spawn_processing(store: SessionStore, id: Uuid) { let _ = thread::Builder::new().name(format!("pssst-processing-{id}")).spawn(move || { let mut failures = 0u32; loop { let live = store.load(&id).map(|s| s.recording_state == RecordingState::Recording).unwrap_or(false); match process_once(&store, id, !live) { Ok(()) => failures = 0, Err(error) => { failures = failures.saturating_add(1); eprintln!("pssst processing: {error:#}"); } } if !live { break; } thread::sleep(Duration::from_secs(2u64.saturating_pow(failures.min(4)))); } }); }
pub fn resume_pending(store: SessionStore) { let directory = store.root().join("sessions"); if let Ok(entries) = fs::read_dir(directory) { for entry in entries.flatten() { if let Ok(id) = Uuid::parse_str(&entry.file_name().to_string_lossy()) { if store.queue_path(&id).exists() { spawn_processing(store.clone(), id); } } } } }

fn process_once(store: &SessionStore, id: Uuid, finalizing: bool) -> Result<()> { let session = store.load(&id)?; let source = store.track_path(&session, TrackKind::Application)?; let mut queue = refresh_queue(store, id, &source, finalizing)?; let (base, secret) = server_connection()?; let client = Client::builder().timeout(Duration::from_secs(120)).default_headers({ let mut h=reqwest::header::HeaderMap::new(); h.insert(reqwest::header::AUTHORIZATION, format!("Bearer {secret}").parse()?); h }).build()?; client.post(format!("{base}/v1/sessions/{id}")).send()?.error_for_status()?;
for index in 0..queue.items.len() { if queue.items[index].state == "complete" { continue; } queue.items[index].attempts += 1; queue.items[index].state = "uploading".into(); save(store,id,&queue)?; let item = queue.items[index].clone(); match upload(&client,&base,id,&item) { Ok(()) => { queue.items[index].state="complete".into(); queue.items[index].last_error=None; save(store,id,&queue)?; sync(&client,&base,store,id)?; }, Err(error) => { queue.items[index].state="retry".into(); queue.items[index].last_error=Some(error.to_string()); save(store,id,&queue)?; let mut s=store.load(&id)?; s.transcription_state=TrackProcessingState::Failed; s.last_error=queue.items[index].last_error.clone(); store.save(&s)?; return Err(error); } } }
let mut s=store.load(&id)?; s.transcription_state=TrackProcessingState::Uploaded; store.save(&s)?; if finalizing { let _=client.post(format!("{base}/v1/sessions/{id}/correct?final=true")).send(); let _=sync(&client,&base,store,id); } Ok(()) }
fn refresh_queue(store:&SessionStore,id:Uuid,source:&PathBuf,finalizing:bool)->Result<Queue>{let path=store.queue_path(&id);let mut queue=if path.exists(){serde_json::from_slice(&fs::read(&path)?)?}else{Queue{items:vec![]}};let data=fs::read(source)?;if data.len()<=WAV_HEADER{return Ok(queue)};let payload=&data[WAV_HEADER..];let bytes=if finalizing{payload.len()}else{payload.len()/ (CHUNK_SECONDS*BYTES_PER_SECOND)*(CHUNK_SECONDS*BYTES_PER_SECOND)};let dir=source.parent().context("track parent")?.join("chunks");fs::create_dir_all(&dir)?;for(sequence,part)in payload[..bytes].chunks(CHUNK_SECONDS*BYTES_PER_SECOND).enumerate(){if queue.items.iter().any(|item|item.sequence==sequence){continue}let target=dir.join(format!("{sequence:06}.wav"));wav(&target,part)?;queue.items.push(QueueItem{sequence,start_ms:(sequence*CHUNK_SECONDS*1000)as i64,end_ms:((sequence*CHUNK_SECONDS*1000)+(part.len()*1000/BYTES_PER_SECOND))as i64,path:target.to_string_lossy().into(),state:"queued".into(),attempts:0,last_error:None});}queue.items.sort_by_key(|item|item.sequence);save(store,id,&queue)?;Ok(queue)}
fn wav(path:&PathBuf,data:&[u8])->Result<()> {let mut f=fs::File::create(path)?;let ch=2u16;let rate=48_000u32;let bits=16u16;let br=rate*ch as u32*bits as u32/8;let align=ch*bits/8;f.write_all(b"RIFF")?;f.write_all(&(36+data.len()as u32).to_le_bytes())?;f.write_all(b"WAVEfmt ")?;f.write_all(&16u32.to_le_bytes())?;f.write_all(&1u16.to_le_bytes())?;f.write_all(&ch.to_le_bytes())?;f.write_all(&rate.to_le_bytes())?;f.write_all(&br.to_le_bytes())?;f.write_all(&align.to_le_bytes())?;f.write_all(&bits.to_le_bytes())?;f.write_all(b"data")?;f.write_all(&(data.len()as u32).to_le_bytes())?;f.write_all(data)?;f.sync_all()?;Ok(())}
fn upload(c:&Client,b:&str,id:Uuid,item:&QueueItem)->Result<()>{let f=fs::File::open(&item.path)?;let form=multipart::Form::new().part("audio",multipart::Part::reader(f).file_name(format!("{}.wav",item.sequence)));c.post(format!("{b}/v1/sessions/{id}/chunks/{}",item.sequence)).multipart(form).send()?.error_for_status()?;c.post(format!("{b}/v1/sessions/{id}/chunks/{}/transcribe",item.sequence)).send()?.error_for_status()?;Ok(())}
fn sync(c:&Client,b:&str,store:&SessionStore,id:Uuid)->Result<()>{#[derive(Deserialize)]struct Row{id:String,start_ms:i64,end_ms:i64,raw_text:String,corrected_text:Option<String>,final_text:Option<String>}let rows:Vec<Row>=c.get(format!("{b}/v1/sessions/{id}/transcript")).send()?.error_for_status()?.json()?;let mut s=store.load(&id)?;for row in rows{if !s.transcript_segments.iter().any(|x|x.backend_id==row.id){s.transcript_segments.push(LocalTranscriptSegment{backend_id:row.id,start_ms:row.start_ms,end_ms:row.end_ms,raw_text:row.raw_text,corrected_text:row.corrected_text,final_text:row.final_text});}}s.transcript_segments.sort_by_key(|x|x.start_ms);store.save(&s)?;Ok(())}
fn save(store:&SessionStore,id:Uuid,q:&Queue)->Result<()>{let path=store.queue_path(&id);let temp=path.with_extension("tmp");fs::write(&temp,serde_json::to_vec_pretty(q)?)?;fs::rename(temp,path)?;Ok(())}
fn server_connection() -> Result<(String, String)> { let link = std::env::var("PSSST_CONNECTION_LINK").context("No pssst connection link configured")?; let (base, secret) = link.rsplit_once("/connect/").context("Invalid pssst connection link")?; if secret.len() < 32 { anyhow::bail!("Invalid pssst connection link") } Ok((base.trim_end_matches('/').into(), secret.into())) }
